version: "3"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    networks:
      - spring_net

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
    depends_on:
      - database

networks:
  spring_net:
